version: "3"
services:
  profilesystem:
    build: .
    ports:
      - 8083:8083
    tty: true
    links:
      - mongodb
    environment:
      - DB_HOST=mongodb
    networks:
      - backend
  mongodb:
    image: mongo:4.2.2-bionic
    container_name: "mongodb"
    ports:
      - 27017:27017
    networks:
      - backend
networks:
  backend: